        <header id="header">
            <!--                                                         -->
            <!-- There are three main div sections - one for the image   -->
            <!-- one for name/assignment (two further divs) and one for  -->
            <!-- the University of Liverpool logo.                       -->
            <!--                                                         -->
            <div id="headerImageDiv">
                <img src="images/siteLogo.png"
                     alt="Site Logo"
                     width=104
                     height=74
                     />
            </div>
            <div id="headerStudentInfoDiv">
                <div id="studentNameDiv">
                    David J. Sanders - MySQL Integration
                </div>
                <div id="assignmentTitleDiv">
                    CKIT503 Programming the Internet: Week 6 - Hand In Assignment
                </div>
            </div>
            <div id="universityLogoDiv">
                <img src="images/uol_logo.png" width="220" height="56" alt="University of Liverpool Logo"/>
            </div>
        </header>
